// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/splitter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SplitterService_HandleDocuments_FullMethodName = "/parser.SplitterService/HandleDocuments"
)

// SplitterServiceClient is the client API for SplitterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SplitterServiceClient interface {
	HandleDocuments(ctx context.Context, in *DocumentArray, opts ...grpc.CallOption) (*Empty, error)
}

type splitterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSplitterServiceClient(cc grpc.ClientConnInterface) SplitterServiceClient {
	return &splitterServiceClient{cc}
}

func (c *splitterServiceClient) HandleDocuments(ctx context.Context, in *DocumentArray, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SplitterService_HandleDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SplitterServiceServer is the server API for SplitterService service.
// All implementations must embed UnimplementedSplitterServiceServer
// for forward compatibility.
type SplitterServiceServer interface {
	HandleDocuments(context.Context, *DocumentArray) (*Empty, error)
	mustEmbedUnimplementedSplitterServiceServer()
}

// UnimplementedSplitterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSplitterServiceServer struct{}

func (UnimplementedSplitterServiceServer) HandleDocuments(context.Context, *DocumentArray) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleDocuments not implemented")
}
func (UnimplementedSplitterServiceServer) mustEmbedUnimplementedSplitterServiceServer() {}
func (UnimplementedSplitterServiceServer) testEmbeddedByValue()                         {}

// UnsafeSplitterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SplitterServiceServer will
// result in compilation errors.
type UnsafeSplitterServiceServer interface {
	mustEmbedUnimplementedSplitterServiceServer()
}

func RegisterSplitterServiceServer(s grpc.ServiceRegistrar, srv SplitterServiceServer) {
	// If the following call pancis, it indicates UnimplementedSplitterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SplitterService_ServiceDesc, srv)
}

func _SplitterService_HandleDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentArray)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SplitterServiceServer).HandleDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SplitterService_HandleDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SplitterServiceServer).HandleDocuments(ctx, req.(*DocumentArray))
	}
	return interceptor(ctx, in, info, handler)
}

// SplitterService_ServiceDesc is the grpc.ServiceDesc for SplitterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SplitterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parser.SplitterService",
	HandlerType: (*SplitterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleDocuments",
			Handler:    _SplitterService_HandleDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/splitter.proto",
}
