// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/auth/auth.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultError_Code int32

const (
	DefaultError_INTERNAL_ERROR DefaultError_Code = 0
	DefaultError_INVALID_DATA   DefaultError_Code = 1
)

// Enum value maps for DefaultError_Code.
var (
	DefaultError_Code_name = map[int32]string{
		0: "INTERNAL_ERROR",
		1: "INVALID_DATA",
	}
	DefaultError_Code_value = map[string]int32{
		"INTERNAL_ERROR": 0,
		"INVALID_DATA":   1,
	}
)

func (x DefaultError_Code) Enum() *DefaultError_Code {
	p := new(DefaultError_Code)
	*p = x
	return p
}

func (x DefaultError_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefaultError_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_auth_proto_enumTypes[0].Descriptor()
}

func (DefaultError_Code) Type() protoreflect.EnumType {
	return &file_proto_auth_auth_proto_enumTypes[0]
}

func (x DefaultError_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefaultError_Code.Descriptor instead.
func (DefaultError_Code) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{3, 0}
}

type AuthError_Code int32

const (
	AuthError_UNKNOWN       AuthError_Code = 0
	AuthError_TOKEN_EXPIRED AuthError_Code = 1
	AuthError_INVALID_TOKEN AuthError_Code = 2
)

// Enum value maps for AuthError_Code.
var (
	AuthError_Code_name = map[int32]string{
		0: "UNKNOWN",
		1: "TOKEN_EXPIRED",
		2: "INVALID_TOKEN",
	}
	AuthError_Code_value = map[string]int32{
		"UNKNOWN":       0,
		"TOKEN_EXPIRED": 1,
		"INVALID_TOKEN": 2,
	}
)

func (x AuthError_Code) Enum() *AuthError_Code {
	p := new(AuthError_Code)
	*p = x
	return p
}

func (x AuthError_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthError_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_auth_proto_enumTypes[1].Descriptor()
}

func (AuthError_Code) Type() protoreflect.EnumType {
	return &file_proto_auth_auth_proto_enumTypes[1]
}

func (x AuthError_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthError_Code.Descriptor instead.
func (AuthError_Code) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{6, 0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_proto_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{2}
}

type DefaultError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          DefaultError_Code      `protobuf:"varint,1,opt,name=code,proto3,enum=pb.DefaultError_Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultError) Reset() {
	*x = DefaultError{}
	mi := &file_proto_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultError) ProtoMessage() {}

func (x *DefaultError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultError.ProtoReflect.Descriptor instead.
func (*DefaultError) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *DefaultError) GetCode() DefaultError_Code {
	if x != nil {
		return x.Code
	}
	return DefaultError_INTERNAL_ERROR
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Status:
	//
	//	*RegisterResponse_Success
	//	*RegisterResponse_Error
	Status        isRegisterResponse_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetStatus() isRegisterResponse_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RegisterResponse) GetSuccess() *Empty {
	if x != nil {
		if x, ok := x.Status.(*RegisterResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *RegisterResponse) GetError() *DefaultError {
	if x != nil {
		if x, ok := x.Status.(*RegisterResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isRegisterResponse_Status interface {
	isRegisterResponse_Status()
}

type RegisterResponse_Success struct {
	Success *Empty `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type RegisterResponse_Error struct {
	Error *DefaultError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*RegisterResponse_Success) isRegisterResponse_Status() {}

func (*RegisterResponse_Error) isRegisterResponse_Status() {}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Status:
	//
	//	*LoginResponse_Token
	//	*LoginResponse_Error
	Status        isLoginResponse_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetStatus() isLoginResponse_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *LoginResponse) GetToken() *Token {
	if x != nil {
		if x, ok := x.Status.(*LoginResponse_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *LoginResponse) GetError() *DefaultError {
	if x != nil {
		if x, ok := x.Status.(*LoginResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isLoginResponse_Status interface {
	isLoginResponse_Status()
}

type LoginResponse_Token struct {
	Token *Token `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type LoginResponse_Error struct {
	Error *DefaultError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*LoginResponse_Token) isLoginResponse_Status() {}

func (*LoginResponse_Error) isLoginResponse_Status() {}

type AuthError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          AuthError_Code         `protobuf:"varint,1,opt,name=code,proto3,enum=pb.AuthError_Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthError) Reset() {
	*x = AuthError{}
	mi := &file_proto_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthError) ProtoMessage() {}

func (x *AuthError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthError.ProtoReflect.Descriptor instead.
func (*AuthError) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *AuthError) GetCode() AuthError_Code {
	if x != nil {
		return x.Code
	}
	return AuthError_UNKNOWN
}

type AuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Status:
	//
	//	*AuthResponse_Success
	//	*AuthResponse_Error
	Status        isAuthResponse_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *AuthResponse) GetStatus() isAuthResponse_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AuthResponse) GetSuccess() *Empty {
	if x != nil {
		if x, ok := x.Status.(*AuthResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *AuthResponse) GetError() *AuthError {
	if x != nil {
		if x, ok := x.Status.(*AuthResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isAuthResponse_Status interface {
	isAuthResponse_Status()
}

type AuthResponse_Success struct {
	Success *Empty `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type AuthResponse_Error struct {
	Error *AuthError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*AuthResponse_Success) isAuthResponse_Status() {}

func (*AuthResponse_Error) isAuthResponse_Status() {}

var File_proto_auth_auth_proto protoreflect.FileDescriptor

const file_proto_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x15proto/auth/auth.proto\x12\x02pb\"8\n" +
	"\x04User\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x1d\n" +
	"\x05Token\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\a\n" +
	"\x05Empty\"g\n" +
	"\fDefaultError\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.pb.DefaultError.CodeR\x04code\",\n" +
	"\x04Code\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x00\x12\x10\n" +
	"\fINVALID_DATA\x10\x01\"m\n" +
	"\x10RegisterResponse\x12%\n" +
	"\asuccess\x18\x01 \x01(\v2\t.pb.EmptyH\x00R\asuccess\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\x10.pb.DefaultErrorH\x00R\x05errorB\b\n" +
	"\x06status\"f\n" +
	"\rLoginResponse\x12!\n" +
	"\x05token\x18\x01 \x01(\v2\t.pb.TokenH\x00R\x05token\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\x10.pb.DefaultErrorH\x00R\x05errorB\b\n" +
	"\x06status\"n\n" +
	"\tAuthError\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.pb.AuthError.CodeR\x04code\"9\n" +
	"\x04Code\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x11\n" +
	"\rTOKEN_EXPIRED\x10\x01\x12\x11\n" +
	"\rINVALID_TOKEN\x10\x02\"f\n" +
	"\fAuthResponse\x12%\n" +
	"\asuccess\x18\x01 \x01(\v2\t.pb.EmptyH\x00R\asuccess\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\r.pb.AuthErrorH\x00R\x05errorB\b\n" +
	"\x06status2j\n" +
	"\vAuthService\x12\x1f\n" +
	"\bRegister\x12\b.pb.User\x1a\t.pb.Empty\x12\x1c\n" +
	"\x05Login\x12\b.pb.User\x1a\t.pb.Token\x12\x1c\n" +
	"\x04Auth\x12\t.pb.Token\x1a\t.pb.EmptyB*Z(github.com/child6yo/rago/services/pkg/pbb\x06proto3"

var (
	file_proto_auth_auth_proto_rawDescOnce sync.Once
	file_proto_auth_auth_proto_rawDescData []byte
)

func file_proto_auth_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_auth_proto_rawDesc), len(file_proto_auth_auth_proto_rawDesc)))
	})
	return file_proto_auth_auth_proto_rawDescData
}

var file_proto_auth_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_auth_auth_proto_goTypes = []any{
	(DefaultError_Code)(0),   // 0: pb.DefaultError.Code
	(AuthError_Code)(0),      // 1: pb.AuthError.Code
	(*User)(nil),             // 2: pb.User
	(*Token)(nil),            // 3: pb.Token
	(*Empty)(nil),            // 4: pb.Empty
	(*DefaultError)(nil),     // 5: pb.DefaultError
	(*RegisterResponse)(nil), // 6: pb.RegisterResponse
	(*LoginResponse)(nil),    // 7: pb.LoginResponse
	(*AuthError)(nil),        // 8: pb.AuthError
	(*AuthResponse)(nil),     // 9: pb.AuthResponse
}
var file_proto_auth_auth_proto_depIdxs = []int32{
	0,  // 0: pb.DefaultError.code:type_name -> pb.DefaultError.Code
	4,  // 1: pb.RegisterResponse.success:type_name -> pb.Empty
	5,  // 2: pb.RegisterResponse.error:type_name -> pb.DefaultError
	3,  // 3: pb.LoginResponse.token:type_name -> pb.Token
	5,  // 4: pb.LoginResponse.error:type_name -> pb.DefaultError
	1,  // 5: pb.AuthError.code:type_name -> pb.AuthError.Code
	4,  // 6: pb.AuthResponse.success:type_name -> pb.Empty
	8,  // 7: pb.AuthResponse.error:type_name -> pb.AuthError
	2,  // 8: pb.AuthService.Register:input_type -> pb.User
	2,  // 9: pb.AuthService.Login:input_type -> pb.User
	3,  // 10: pb.AuthService.Auth:input_type -> pb.Token
	4,  // 11: pb.AuthService.Register:output_type -> pb.Empty
	3,  // 12: pb.AuthService.Login:output_type -> pb.Token
	4,  // 13: pb.AuthService.Auth:output_type -> pb.Empty
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_auth_auth_proto_init() }
func file_proto_auth_auth_proto_init() {
	if File_proto_auth_auth_proto != nil {
		return
	}
	file_proto_auth_auth_proto_msgTypes[4].OneofWrappers = []any{
		(*RegisterResponse_Success)(nil),
		(*RegisterResponse_Error)(nil),
	}
	file_proto_auth_auth_proto_msgTypes[5].OneofWrappers = []any{
		(*LoginResponse_Token)(nil),
		(*LoginResponse_Error)(nil),
	}
	file_proto_auth_auth_proto_msgTypes[7].OneofWrappers = []any{
		(*AuthResponse_Success)(nil),
		(*AuthResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_auth_proto_rawDesc), len(file_proto_auth_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_auth_proto_depIdxs,
		EnumInfos:         file_proto_auth_auth_proto_enumTypes,
		MessageInfos:      file_proto_auth_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_auth_proto = out.File
	file_proto_auth_auth_proto_goTypes = nil
	file_proto_auth_auth_proto_depIdxs = nil
}
