// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: storage/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collectionName,proto3" json:"collectionName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollectionRequest) Reset() {
	*x = CollectionRequest{}
	mi := &file_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionRequest) ProtoMessage() {}

func (x *CollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionRequest.ProtoReflect.Descriptor instead.
func (*CollectionRequest) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

type DocumentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collectionName,proto3" json:"collectionName,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DocumentRequest) Reset() {
	*x = DocumentRequest{}
	mi := &file_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentRequest) ProtoMessage() {}

func (x *DocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentRequest.ProtoReflect.Descriptor instead.
func (*DocumentRequest) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *DocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	CollectionName string                 `protobuf:"bytes,3,opt,name=collectionName,proto3" json:"collectionName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *Metadata) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_storage_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{4}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Document) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Document) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type DocumentArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      []*Document            `protobuf:"bytes,1,rep,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentArray) Reset() {
	*x = DocumentArray{}
	mi := &file_storage_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentArray) ProtoMessage() {}

func (x *DocumentArray) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentArray.ProtoReflect.Descriptor instead.
func (*DocumentArray) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{5}
}

func (x *DocumentArray) GetDocument() []*Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      []*Document            `protobuf:"bytes,1,rep,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_storage_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{6}
}

func (x *QueryResponse) GetDocument() []*Document {
	if x != nil {
		return x.Document
	}
	return nil
}

var File_storage_storage_proto protoreflect.FileDescriptor

const file_storage_storage_proto_rawDesc = "" +
	"\n" +
	"\x15storage/storage.proto\x12\astorage\x1a\x1bgoogle/protobuf/empty.proto\";\n" +
	"\x11CollectionRequest\x12&\n" +
	"\x0ecollectionName\x18\x01 \x01(\tR\x0ecollectionName\"I\n" +
	"\x0fDocumentRequest\x12&\n" +
	"\x0ecollectionName\x18\x01 \x01(\tR\x0ecollectionName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"b\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12&\n" +
	"\x0ecollectionName\x18\x03 \x01(\tR\x0ecollectionName\"\x1c\n" +
	"\bMetadata\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"y\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12-\n" +
	"\bmetadata\x18\x03 \x01(\v2\x11.storage.MetadataR\bmetadata\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\">\n" +
	"\rDocumentArray\x12-\n" +
	"\bdocument\x18\x01 \x03(\v2\x11.storage.DocumentR\bdocument\">\n" +
	"\rQueryResponse\x12-\n" +
	"\bdocument\x18\x01 \x03(\v2\x11.storage.DocumentR\bdocument2\xa0\x03\n" +
	"\x0eStorageService\x12F\n" +
	"\x10CreateCollection\x12\x1a.storage.CollectionRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x10DeleteCollection\x12\x1a.storage.CollectionRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x0eDeleteDocument\x12\x18.storage.DocumentRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\vGetDocument\x12\x18.storage.DocumentRequest\x1a\x11.storage.Document\x12E\n" +
	"\x0fGetAllDocuments\x12\x1a.storage.CollectionRequest\x1a\x16.storage.DocumentArray\x127\n" +
	"\x06Search\x12\x15.storage.QueryRequest\x1a\x16.storage.QueryResponseB(Z&github.com/child6yo/rago/proto/storageb\x06proto3"

var (
	file_storage_storage_proto_rawDescOnce sync.Once
	file_storage_storage_proto_rawDescData []byte
)

func file_storage_storage_proto_rawDescGZIP() []byte {
	file_storage_storage_proto_rawDescOnce.Do(func() {
		file_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_storage_proto_rawDesc), len(file_storage_storage_proto_rawDesc)))
	})
	return file_storage_storage_proto_rawDescData
}

var file_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_storage_storage_proto_goTypes = []any{
	(*CollectionRequest)(nil), // 0: storage.CollectionRequest
	(*DocumentRequest)(nil),   // 1: storage.DocumentRequest
	(*QueryRequest)(nil),      // 2: storage.QueryRequest
	(*Metadata)(nil),          // 3: storage.Metadata
	(*Document)(nil),          // 4: storage.Document
	(*DocumentArray)(nil),     // 5: storage.DocumentArray
	(*QueryResponse)(nil),     // 6: storage.QueryResponse
	(*emptypb.Empty)(nil),     // 7: google.protobuf.Empty
}
var file_storage_storage_proto_depIdxs = []int32{
	3, // 0: storage.Document.metadata:type_name -> storage.Metadata
	4, // 1: storage.DocumentArray.document:type_name -> storage.Document
	4, // 2: storage.QueryResponse.document:type_name -> storage.Document
	0, // 3: storage.StorageService.CreateCollection:input_type -> storage.CollectionRequest
	0, // 4: storage.StorageService.DeleteCollection:input_type -> storage.CollectionRequest
	1, // 5: storage.StorageService.DeleteDocument:input_type -> storage.DocumentRequest
	1, // 6: storage.StorageService.GetDocument:input_type -> storage.DocumentRequest
	0, // 7: storage.StorageService.GetAllDocuments:input_type -> storage.CollectionRequest
	2, // 8: storage.StorageService.Search:input_type -> storage.QueryRequest
	7, // 9: storage.StorageService.CreateCollection:output_type -> google.protobuf.Empty
	7, // 10: storage.StorageService.DeleteCollection:output_type -> google.protobuf.Empty
	7, // 11: storage.StorageService.DeleteDocument:output_type -> google.protobuf.Empty
	4, // 12: storage.StorageService.GetDocument:output_type -> storage.Document
	5, // 13: storage.StorageService.GetAllDocuments:output_type -> storage.DocumentArray
	6, // 14: storage.StorageService.Search:output_type -> storage.QueryResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_storage_storage_proto_init() }
func file_storage_storage_proto_init() {
	if File_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_storage_proto_rawDesc), len(file_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_storage_proto_goTypes,
		DependencyIndexes: file_storage_storage_proto_depIdxs,
		MessageInfos:      file_storage_storage_proto_msgTypes,
	}.Build()
	File_storage_storage_proto = out.File
	file_storage_storage_proto_goTypes = nil
	file_storage_storage_proto_depIdxs = nil
}
