openapi: "3.0.3"
info:
  title: RAGO
  version: "1.0"
servers:
  - url: http://example.com/api/v1
tags:
  - name: Storage
    description: Operations related to managing data in the vector database.

paths:
  /storage:
    post:
      tags:
        - Retriever
      summary: Adds a new entry to the vector database.
      description: |
        Example request:
        ```
          POST http://example.com/api/v1/storage
        ```
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  chunk:
                    type: string
                    example: "The Cocoanuts is a 1929 pre-Code musical comedy film starring the Marx Brothers"
                  metadata:
                    type: string
                    example: "url:https://en.wikipedia.org/wiki/The_Cocoanuts"
              example:
                - {
                    chunk: "The Cocoanuts is a 1929 pre-Code musical comedy film starring the Marx Brothers",
                    metadata:
                      { url: "https://en.wikipedia.org/wiki/The_Cocoanuts" },
                  }
                - { chunk: "bla bla", metadata: { url: "value" } }
      responses:
        "202":
          description: Accepted
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                items:
                  properties:
                    error:
                      type: string
                      example: "error description"
                example:
                  error: "error description"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                items:
                  properties:
                    error:
                      type: string
                      example: "error description"
                example:
                  error: "error description"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                items:
                  properties:
                    error:
                      type: string
                      example: "error description"
                example:
                  error: "error description"
