// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/splitter.proto

package splitter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_splitter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_splitter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_splitter_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_splitter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_splitter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_splitter_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Document) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DocumentArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doc           []*Document            `protobuf:"bytes,1,rep,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentArray) Reset() {
	*x = DocumentArray{}
	mi := &file_proto_splitter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentArray) ProtoMessage() {}

func (x *DocumentArray) ProtoReflect() protoreflect.Message {
	mi := &file_proto_splitter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentArray.ProtoReflect.Descriptor instead.
func (*DocumentArray) Descriptor() ([]byte, []int) {
	return file_proto_splitter_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentArray) GetDoc() []*Document {
	if x != nil {
		return x.Doc
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_splitter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_splitter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_splitter_proto_rawDescGZIP(), []int{3}
}

var File_proto_splitter_proto protoreflect.FileDescriptor

const file_proto_splitter_proto_rawDesc = "" +
	"\n" +
	"\x14proto/splitter.proto\x12\x06parser\"\x1c\n" +
	"\bMetadata\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"R\n" +
	"\bDocument\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12,\n" +
	"\bmetadata\x18\x02 \x01(\v2\x10.parser.MetadataR\bmetadata\"3\n" +
	"\rDocumentArray\x12\"\n" +
	"\x03doc\x18\x01 \x03(\v2\x10.parser.DocumentR\x03doc\"\a\n" +
	"\x05Empty2J\n" +
	"\x0fSplitterService\x127\n" +
	"\x0fHandleDocuments\x12\x15.parser.DocumentArray\x1a\r.parser.EmptyB0Z.github.com/child6yo/rago/services/parser/protob\x06proto3"

var (
	file_proto_splitter_proto_rawDescOnce sync.Once
	file_proto_splitter_proto_rawDescData []byte
)

func file_proto_splitter_proto_rawDescGZIP() []byte {
	file_proto_splitter_proto_rawDescOnce.Do(func() {
		file_proto_splitter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_splitter_proto_rawDesc), len(file_proto_splitter_proto_rawDesc)))
	})
	return file_proto_splitter_proto_rawDescData
}

var file_proto_splitter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_splitter_proto_goTypes = []any{
	(*Metadata)(nil),      // 0: parser.Metadata
	(*Document)(nil),      // 1: parser.Document
	(*DocumentArray)(nil), // 2: parser.DocumentArray
	(*Empty)(nil),         // 3: parser.Empty
}
var file_proto_splitter_proto_depIdxs = []int32{
	0, // 0: parser.Document.metadata:type_name -> parser.Metadata
	1, // 1: parser.DocumentArray.doc:type_name -> parser.Document
	2, // 2: parser.SplitterService.HandleDocuments:input_type -> parser.DocumentArray
	3, // 3: parser.SplitterService.HandleDocuments:output_type -> parser.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_splitter_proto_init() }
func file_proto_splitter_proto_init() {
	if File_proto_splitter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_splitter_proto_rawDesc), len(file_proto_splitter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_splitter_proto_goTypes,
		DependencyIndexes: file_proto_splitter_proto_depIdxs,
		MessageInfos:      file_proto_splitter_proto_msgTypes,
	}.Build()
	File_proto_splitter_proto = out.File
	file_proto_splitter_proto_goTypes = nil
	file_proto_splitter_proto_depIdxs = nil
}
