up:
	migrate -path ./schemas -database 'postgres://postgres:Qwerty@localhost:5432/postgres?sslmode=disable' up
down:
	migrate -path ./schemas -database 'postgres://postgres:Qwerty@localhost:5432/postgres?sslmode=disable' down